### ISSUE TITLE
Plugin breaks admin-ajax.php

### ISSUE THREAD

**Issue by mrazzari** [publicmediaplatform/pmp-wordpress#111]
We were having an issue where users of the WP-Admin would not see any media items in the "grid" view under Media > Library.

This was "fixed" by disabling this PMP plugin. 

I haven't attempted to debug this at all, but looking at the trace, maybe it was caused by the plugin not being configured at all? (We had simply installed it, but didn't set any user/pass etc.)

```
[Mon Sep 28 15:31:42.732788 2015] [:error] [pid 10946] 

PHP Fatal error: Uncaught exception 'Pmp\\Sdk\\Exception\\LinkException' with message 'Unable to retrieve urn:collectiondoc:form:issuetoken from the home document' in /nas/wp/www/cluster-42475/www/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/AuthClient.php:94

Stack trace:
#0 /nas/wp/www/cluster-42475/www/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/AuthClient.php(74): Pmp\\Sdk\\AuthClient->_authLink('urn:collectiond...', Array)
#1 /nas/wp/www/cluster-42475/www/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/AuthClient.php(45): Pmp\\Sdk\\AuthClient->_request('urn:collectiond...', Array)
#2 /nas/wp/www/cluster-42475/www/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/AuthClient.php(33): Pmp\\Sdk\\AuthClient->getToken()
#3 /nas/wp/www/cluster-42475/www/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk.php(56 in /nas/wp/www/cluster-42475/www/wp-content/plugins/public-media-platform/vendor/publicmediaplatform/pmpsdk/src/Pmp/Sdk/AuthClient.php on line 94, referer: /wp-admin/upload.php```

**Comment by cavis** [comment]
Yeah - I think your guess is correct.

The PMP plugin adds a filter to media items, to remove any images downloaded from the PMP.  (The logic being that "you shouldn't be using PMP-images in non-PMP Posts").

It seems the filter isn't actually checking if you've setup your PMP host/credentials - it's just attempting to make a query to the PMP.

Should throw a conditional around this filter, to make sure you've configured the plugin first.
